# Generated by Django 5.2.11 on 2026-02-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quantidade_criancas', models.PositiveIntegerField()),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
